name: example

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  pedantic: ^1.8.0
  test: ^1.6.0

dependency_overrides:
  json_annotation:
    git:
      url: https://github.com/dart-lang/json_serializable.git
      ref: patch-files
      path: json_annotation
  json_serializable:
    git:
      url: https://github.com/dart-lang/json_serializable.git
      ref: patch-files
      path: json_serializable
